name: Deploy notebook

on:
  schedule:
    - cron: '0 6 1,15 * *'  # 1st and 15th of each month
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    uses: data-desk-eco/.github/.github/workflows/notebook-deploy.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets: inherit
